project:
  type: website
  output-dir: docs

website:
  title: "assignment-3-trb238"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



